# Generated by Django 5.0.6 on 2024-06-23 08:59

import autoslug.fields
import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('body', models.TextField(max_length=1000)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.CharField(blank=True, max_length=10000)),
                ('queryn', models.CharField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('user', models.CharField(default=None, max_length=70)),
                ('post_img', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, max_length=100000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('body', models.TextField(max_length=100000)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('likes', models.ManyToManyField(related_name='post_query', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
