# Generated by Django 5.0.6 on 2024-06-24 16:49

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('experience', models.TextField(max_length=600)),
                ('detail', models.TextField(max_length=2000)),
                ('post_img', models.ImageField(blank=True, null=True, upload_to='dpost_images')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
            ],
        ),
    ]
